language: php
php:
  - 5.6
  - 7.0

script:
  - composer install
  - php vendor/bin/phpcs --standard=PSR2 src tests
  - php vendor/bin/phpunit --testsuite tests --coverage-text

cache:
  directories:
    - vendor
