sudo: false
os: linux
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - make test

after_success:
  - if [[ "7.2" == "${TRAVIS_PHP_VERSION}" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
